// components/emails/welcome-email.tsx
import * as React from "react";

interface WelcomeEmailProps {
  name: string;
  email: string;
}

export function WelcomeEmail({ name, email }: WelcomeEmailProps) {
  const displayName = name || email.split("@")[0];

  return (
    <div
      style={{
        fontFamily: "'Segoe UI', Arial, sans-serif",
        maxWidth: "600px",
        margin: "0 auto",
        backgroundColor: "#ffffff",
      }}
    >
      {/* Header */}
      <div
        style={{
          backgroundColor: "#3b82f6",
          borderRadius: "12px 12px 0 0",
          padding: "40px 40px 32px",
          textAlign: "center",
        }}
      >
        <div
          style={{
            display: "inline-flex",
            alignItems: "center",
            gap: "10px",
            marginBottom: "16px",
          }}
        >
          <div
            style={{
              width: "36px",
              height: "36px",
              backgroundColor: "rgba(255,255,255,0.25)",
              borderRadius: "8px",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              fontSize: "18px",
            }}
          >
            🍼
          </div>
          <div style={{ textAlign: "left" }}>
            <p
              style={{
                color: "#ffffff",
                fontWeight: 700,
                fontSize: "15px",
                margin: 0,
                lineHeight: 1,
              }}
            >
              AI Insight
            </p>
            <p
              style={{
                color: "rgba(255,255,255,0.75)",
                fontSize: "10px",
                letterSpacing: "3px",
                margin: 0,
                marginTop: "2px",
              }}
            >
              SIMULATOR
            </p>
          </div>
        </div>

        <h1
          style={{
            color: "#ffffff",
            fontSize: "28px",
            fontWeight: 700,
            margin: 0,
            lineHeight: 1.2,
          }}
        >
          Welcome to AI Insight Simulator!
        </h1>
        <p
          style={{
            color: "rgba(255,255,255,0.85)",
            fontSize: "15px",
            marginTop: "10px",
            marginBottom: 0,
          }}
        >
          Your daycare operations are about to get smarter.
        </p>
      </div>

      {/* Body */}
      <div
        style={{
          backgroundColor: "#f8fafc",
          padding: "40px",
          borderRadius: "0 0 12px 12px",
          border: "1px solid #e2e8f0",
          borderTop: "none",
        }}
      >
        <p style={{ color: "#374151", fontSize: "16px", marginTop: 0 }}>
          Hi <strong>{displayName}</strong>,
        </p>
        <p style={{ color: "#6b7280", fontSize: "15px", lineHeight: 1.6 }}>
          Your account has been created successfully. You now have access to the
          full AI Insight Simulator — designed specifically for daycare center
          owners and operators.
        </p>

        {/* Feature list */}
        <div
          style={{
            backgroundColor: "#ffffff",
            border: "1px solid #e5e7eb",
            borderRadius: "10px",
            padding: "24px",
            margin: "24px 0",
          }}
        >
          <p
            style={{
              color: "#111827",
              fontWeight: 600,
              fontSize: "14px",
              marginTop: 0,
              marginBottom: "16px",
            }}
          >
            Here&apos;s what you can do:
          </p>

          {[
            {
              icon: "💰",
              title: "Financial Analysis",
              desc: "Calculate net income, break-even points, and expense ratios for your center.",
            },
            {
              icon: "👥",
              title: "Staffing Optimization",
              desc: "Determine optimal staff levels based on your enrollment numbers.",
            },
            {
              icon: "📈",
              title: "Growth Planning",
              desc: "Simulate expansion scenarios and see projected financial impacts.",
            },
            {
              icon: "🛡️",
              title: "Risk Assessment",
              desc: "Evaluate your center's financial resilience against unexpected events.",
            },
            {
              icon: "🤖",
              title: "AI-Powered Insights",
              desc: "Get personalized recommendations and an action plan generated by AI.",
            },
          ].map((feature) => (
            <div
              key={feature.title}
              style={{
                display: "flex",
                gap: "12px",
                marginBottom: "14px",
                alignItems: "flex-start",
              }}
            >
              <span style={{ fontSize: "20px", lineHeight: 1 }}>{feature.icon}</span>
              <div>
                <p
                  style={{
                    fontWeight: 600,
                    fontSize: "13px",
                    color: "#111827",
                    margin: 0,
                  }}
                >
                  {feature.title}
                </p>
                <p
                  style={{
                    color: "#6b7280",
                    fontSize: "13px",
                    margin: "2px 0 0",
                    lineHeight: 1.5,
                  }}
                >
                  {feature.desc}
                </p>
              </div>
            </div>
          ))}
        </div>

        {/* CTA */}
        <div style={{ textAlign: "center", margin: "28px 0" }}>
          <a
            href={process.env.NEXTAUTH_URL ?? "http://localhost:3000"}
            style={{
              display: "inline-block",
              backgroundColor: "#3b82f6",
              color: "#ffffff",
              fontWeight: 600,
              fontSize: "15px",
              textDecoration: "none",
              padding: "13px 32px",
              borderRadius: "8px",
            }}
          >
            Go to Dashboard →
          </a>
        </div>

        <p
          style={{
            color: "#9ca3af",
            fontSize: "13px",
            textAlign: "center",
            marginBottom: 0,
          }}
        >
          You&apos;re logged in as <strong>{email}</strong>. If you didn&apos;t
          create this account, please ignore this email.
        </p>
      </div>
    </div>
  );
}